FROM node:18

WORKDIR /app

COPY frontend/package*.json ./

RUN npm install --legacy-peer-deps
RUN npm install ajv

COPY frontend/ .

EXPOSE 3000

ENV CI=true
ENV WDS_SOCKET_PORT=0

CMD ["npm", "start"]
